package com.mbp.model.module.client;

import com.mbp.model.module.common.BMPLoginAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 24 17:17:26 CST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BMPLoginAMClient extends ApplicationModuleImpl implements BMPLoginAM {
    /**
     * This is the default constructor (do not remove).
     */
    public BMPLoginAMClient() {
    }


    public String createBooking(String username, String pass, String showTime,
                                String movieName, int price, int tickets) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createBooking",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","int","int"},new Object[] {username, pass, showTime, movieName, new Integer(price), new Integer(tickets)});
        return (String)_ret;
    }


    public boolean findUserByAttr(String username, String passward) {
        Object _ret =
            this.riInvokeExportedMethod(this,"findUserByAttr",new String [] {"java.lang.String","java.lang.String"},new Object[] {username, passward});
        return ((Boolean)_ret).booleanValue();
    }

    public double calDiscountPrice(String username, String password,
                                   int price) {
        Object _ret =
            this.riInvokeExportedMethod(this,"calDiscountPrice",new String [] {"java.lang.String","java.lang.String","int"},new Object[] {username, password, new Integer(price)});
        return ((Double)_ret).doubleValue();
    }

    public int getAvaliableSeat(String showTime, String movieName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getAvaliableSeat",new String [] {"java.lang.String","java.lang.String"},new Object[] {showTime, movieName});
        return ((Integer)_ret).intValue();
    }

    public String createBooking(String username, String pass, String showTime,
                                String movieName, double price, int tickets) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createBooking",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","double","int"},new Object[] {username, pass, showTime, movieName, new Double(price), new Integer(tickets)});
        return (String)_ret;
    }

    public void setBindVariableForFilterMyOrder(String userName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setBindVariableForFilterMyOrder",new String [] {"java.lang.String"},new Object[] {userName});
        return;
    }

    public void updateAvaliableSeat(int seatNumber, int screenNumber,
                                    String showTime) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateAvaliableSeat",new String [] {"int","int","java.lang.String"},new Object[] {new Integer(seatNumber), new Integer(screenNumber), showTime});
        return;
    }
}
