package com.mbp.model.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 24 17:17:26 CST 2017
// ---------------------------------------------------------------------
public interface BMPLoginAM extends ApplicationModule {

    boolean findUserByAttr(String username, String passward);


    double calDiscountPrice(String username, String password, int price);

    int getAvaliableSeat(String showTime, String movieName);

    String createBooking(String username, String pass, String showTime,
                         String movieName, double price, int tickets);

    void setBindVariableForFilterMyOrder(String userName);

    void updateAvaliableSeat(int seatNumber, int screenNumber,
                             String showTime);
}
